DROP TABLE DB_CONSULTATION CASCADE CONSTRAINTS;
DROP TABLE DB_VACCINATION CASCADE CONSTRAINTS;
DROP TABLE DB_MEDICAL_RECORD CASCADE CONSTRAINTS;
DROP TABLE DB_PET CASCADE CONSTRAINTS;
DROP TABLE DB_CLINIC CASCADE CONSTRAINTS;
DROP TABLE DB_VETERINARIAN CASCADE CONSTRAINTS;
DROP TABLE DB_TUTOR CASCADE CONSTRAINTS;


CREATE TABLE DB_TUTOR (
    ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(15) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    PASSWORD VARCHAR2(300) NOT NULL,
    ADDRESS VARCHAR2(400) NOT NULL,
    
    -- PRIMARY KEY
    CONSTRAINT DB_TUTOR_ID_PK PRIMARY KEY (ID),
    
    -- UNIQUES CONSTRAINTS
    CONSTRAINT DB_TUTOR_CPF_UN UNIQUE (CPF),
    CONSTRAINT DB_TUTOR_PHONE_UN UNIQUE (PHONE),
    CONSTRAINT DB_TUTOR_EMAIL_UN UNIQUE (EMAIL)
);

CREATE TABLE DB_VETERINARIAN (
    ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CRMV VARCHAR2(15) NOT NULL,
    SPECIALTY VARCHAR2(50) NOT NULL,
    
    -- PRIMARY KEY
    CONSTRAINT DB_VETERINARIAN_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE DB_CLINIC (
    ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CNPJ VARCHAR2(18) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    
    -- PRIMARY KEY
    CONSTRAINT DB_CLINIC_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE DB_PET (
    ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    ID_TUTOR INTEGER NOT NULL,
    NAME VARCHAR2(100),
    SPECIES VARCHAR2(50) NOT NULL,
    BREED VARCHAR2(50),
    AGE INTEGER,
    WEIGHT NUMBER(5,2),
    SEX VARCHAR2(15) NOT NULL,
    
    -- PRIMARY KEY
    CONSTRAINT DB_PET_ID_PK PRIMARY KEY (ID),
    
    -- FORREIGN KEY
    CONSTRAINT DB_PET_ID_TUTOR_FK FOREIGN KEY (ID_TUTOR) 
    REFERENCES DB_TUTOR (ID)
    
);

CREATE TABLE DB_MEDICAL_RECORD (
    ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    ID_PET INTEGER NOT NULL,
    BLOOD_TYPE VARCHAR2(5) NOT NULL,
    ALLERGIES VARCHAR2(500),
    CHRONIC_DISEASES VARCHAR2(500),
    IS_CASTRATED CHAR(1) DEFAULT 'N',
    MICROCHIP_CODE VARCHAR2(50),
    LAST_UPDATE TIMESTAMP NOT NULL,
    
    -- PRIMARY KEY
    CONSTRAINT DB_MEDICAL_RECORD_ID_PK PRIMARY KEY (ID),
    
    -- FOREIGN KEY
    CONSTRAINT DB_MEDICAL_RECORD_ID_PET_FK FOREIGN KEY (ID_PET)
    REFERENCES DB_PET (ID)
);

CREATE TABLE DB_VACCINATION (
    ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    ID_PET INTEGER NOT NULL,
    VACCINE_NAME VARCHAR2(50) NOT NULL,
    APPLICATION_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE NOT NULL,
    LOT VARCHAR2(10),
    
    --PRIMARY KEY
    CONSTRAINT DB_VACCINATION_ID_PK PRIMARY KEY (ID),
    
    -- FOREIGN KEY
    CONSTRAINT DB_VACCINATION_ID_PET_FK FOREIGN KEY (ID_PET)
    REFERENCES DB_PET (ID)
    
);

CREATE TABLE DB_CONSULTATION (
    ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    ID_MEDICAL_RECORD INTEGER NOT NULL,
    ID_VETERINARIAN INTEGER NOT NULL,
    ID_CLINIC INTEGER NOT NULL,
    CONSULTATION_DATE DATE NOT NULL,
    SYMPTOMS VARCHAR2(100),
    DIAGNOSIS VARCHAR2(200),
    OBSERVATIONS VARCHAR2(500),
    ATTACHMET BLOB,
    
    -- PRIMARY KEY
    CONSTRAINT DB_CONSULTATION_ID_PK PRIMARY KEY (ID),
    
    -- FOREIGN KEYS
    CONSTRAINT DB_CONSULTATION_ID_MEDICAL_RECORD_FK FOREIGN KEY (ID_MEDICAL_RECORD)
    REFERENCES DB_MEDICAL_RECORD (ID),
    CONSTRAINT DB_CONSULTATION_ID_VETERINARIAN_FK FOREIGN KEY (ID_VETERINARIAN)
    REFERENCES DB_VETERINARIAN (ID),
    CONSTRAINT DB_CONSULTATION_ID_CLINIC_FK FOREIGN KEY (ID_CLINIC)
    REFERENCES DB_CLINIC (ID)
);